# #



## Use Node.js v14 as the base image
# FROM node:14

# # Set the working directory
# WORKDIR /app

# # Copy package.json and package-lock.json files
# COPY . /app

# # Install dependencies
# RUN npm install


# # Expose port 3000 for the backend service
# EXPOSE 3000

# # Start the application
# CMD [ "npm", "start" ]


